### PR TITLE
Prevent uneeded call to 'main()' in test

### PR DESCRIPTION
**Pull request by mondeja**
Great job with this project, the code is pretty clear. I've been studiying it a bit and found some strange code.

- When the `src/main.js` file is required in `test/main.test.js`, the `main()` function is executed needlessly.
- ~~The exports of `src/create.js` are a bit weird because other functions are setted as properties to the `makeRelease` function. I'm not sure if this is intentional.~~ (tracked in separate issue)

### CODE REVIEW

**Comment by ericcornelissen** [comment]
> Great job with this project, the code is pretty clear. I've been studiying it a bit and found some strange code.

Thanks, that's good to hear because I felt like it was mostly just hacked together :sweat_smile: 


> When the src/main.js file is required in test/main.test.js, the main() function is executed needlessly.

While I'm not against it necessarily (apart from the fact that I'm not sure how robust your solution is), I see no reason to "fix" this as `src/main.js` is never required outside a test, and running it when testing is not a problem at all. (as a general principle: don't change your code to suite your tests)

I agree that it is a bit strange, but it is (to the best of my knowledge) required to "invoke" something in order to run it with GitHub Actions.

If you want to avoid this scenario, I would prefer we add an `index.js` that imports from `src/main.js` and executes main, and use `index.js` as [the file to compile](https://github.com/simple-icons/release-action/blob/6846e3cc0c1b3d8dc5b013b6dc6e390c09ce4ebe/package.json#L13). How does that sound?


> The exports of src/create.js are a bit weird because other functions are setted as properties to the makeRelease function. I'm not sure if this is intentional.

It is intentional in the sense that I exported the other functions purely to be able to test them. They're not intended for usage. This is a bit of a hack. The proper way to fix this is to remove the exports and update its test suite to be more like [the test suite of `src/merge.js`](https://github.com/simple-icons/release-action/blob/master/test/merge.test.js), and make sure still all the paths covered by the specific test are covered by the overall test. I can look into this if you don't feel familiar enough with the code to do this.

**Comment by ericcornelissen** [comment]
Also, following https://github.com/simple-icons/simple-icons-font/issues/68, now that more than one person is looking at this code we might want to look into using Prettier here as well :thinking:

**Comment by mondeja** [comment]
> Also, following https://github.com/simple-icons/simple-icons-font/issues/68, now that more than one person is looking at this code we might want to look into using Prettier here as well :thinking:

I was thinking the same. Opening another issue to track this...

**Comment by ericcornelissen** [comment]
One more thing, the diff for [`.husky/pre-commit`](https://github.com/simple-icons/release-action/blob/6846e3cc0c1b3d8dc5b013b6dc6e390c09ce4ebe/.husky/pre-commit) looks a bit weird. Did you only change `100644 → 100755`? If so why did you change it? Did you have trouble executing it? (GitHub seems to suggest the file is now empty :confused:)

**Comment by mondeja** [comment]
> One more thing, the diff for [`.husky/pre-commit`](https://github.com/simple-icons/release-action/blob/6846e3cc0c1b3d8dc5b013b6dc6e390c09ce4ebe/.husky/pre-commit) looks a bit weird. Did you only change `100644 → 100755`? If so why did you change it? Did you have trouble executing it? (GitHub seems to suggest the file is now empty :confused:)

GIT reported this problem when I've created the commit the first time:

```
help: The hook '.husky/pre-commit' was ignored because has not been configured as executable.
help: You can disable these warnings with `git config advice.ignoredHook false`.
```

After change permissions with `chmod a+x .husky/pre-commit` has been executed. You can execute it without executable permissions?

**Comment by mondeja** [comment]
> If you want to avoid this scenario, I would prefer we add an index.js that imports from src/main.js and executes main, and use index.js as the file to compile. How does that sound?

Sounds better :+1:

> It is intentional in the sense that I exported the other functions purely to be able to test them. They're not intended for usage. This is a bit of a hack. The proper way to fix this is to remove the exports and update its test suite to be more like the test suite of src/merge.js, and make sure still all the paths covered by the specific test are covered by the overall test. I can look into this if you don't feel familiar enough with the code to do this.

Sure, this would be more reasonable. I suspect that this would be a bit difficult for me now. Maybe we can open another issue to track this refactorization, so I only refactor in this pull the uneeded call to `main()` applying your suggested solution?

**Comment by ericcornelissen** [comment]
> > One more thing, the diff for [`.husky/pre-commit`](https://github.com/simple-icons/release-action/blob/6846e3cc0c1b3d8dc5b013b6dc6e390c09ce4ebe/.husky/pre-commit) looks a bit weird. Did you only change `100644 → 100755`? If so why did you change it? Did you have trouble executing it? (GitHub seems to suggest the file is now empty confused)
> 
> GIT reported this problem when I've created the commit the first time:
> 
> ```
> help: The hook '.husky/pre-commit' was ignored because has not been configured as executable.
> help: You can disable these warnings with `git config advice.ignoredHook false`.
> ```
> 
> After change permissions with `chmod a+x .husky/pre-commit` has been executed. You can execute it without executable permissions?

Interesting, for me the permission flags are `774` after cloning and `npm install`ing :thinking: May depend on the system or git configuration? Anyway, probably a good idea to update them if it doesn't work out of the box for everyone.

Relatedly, what do you think about setting up automatic git hooks for formatting in [the simple-icons-font repository](https://github.com/simple-icons/simple-icons-font)? So far I've stayed away from using them in most projects as, at least for [the main simple-icons project](https://github.com/simple-icons/simple-icons), many contributors will never ever run `npm install`. But it might be worth adding to the font to more strictly enforce the code formatting. If you agree, feel free to open an issue for it :slightly_smiling_face:

**Comment by ericcornelissen** [comment]
> Sure, this would be more reasonable. I suspect that this would be a bit difficult for me now. Maybe we can open another issue to track this refactorization, so I only refactor in this pull the uneeded call to `main()` applying your suggested solution?

Sounds good, just assign me to that issue so I don't forget about it :smile:

**Comment by mondeja** [comment]
> If so why did you change it? Did you have trouble executing it? (GitHub seems to suggest the file is now empty :confused:)

As you can see in my branch, the file [`.husky/pre-commit` is not really empty](https://github.com/mondeja/release-action/blob/refactor-exports/.husky/pre-commit), Github shows "Empty file." in the changes because no changes have been made to the file, only its permissions.

**Review by ericcornelissen — CHANGES_REQUESTED** [review]
Looking good :+1: Could you just update [the `"main"` field of `package.json`](https://github.com/simple-icons/release-action/blob/6846e3cc0c1b3d8dc5b013b6dc6e390c09ce4ebe/package.json#L7) to point to `index.js`? And, depending on what you prefer, `src/index.js` may also be moved to `./index.js`.

**Comment by mondeja** [comment]
> And, depending on what you prefer, `src/index.js` may also be moved to `./index.js`.

I like maintain all the sources in `src/`, but don't bother me put the `index.js` at the root either, so as you prefer...

**Review by ericcornelissen — APPROVED** [review]

**Comment by ericcornelissen** [comment]
> > And, depending on what you prefer, `src/index.js` may also be moved to `./index.js`.
> 
> I like to maintain all the sources in `src/`, but don't bother me put the `index.js` at the root either, so as you prefer...

Let's just keep it like this then, at least for now :slightly_smiling_face:

**Pull request merged**
