### PR TITLE
Fix parameters of `repos.getContent` API

### PR DESCRIPTION
**Pull request by LitoMore**
Closes #88

Fix the failing CI: https://github.com/simple-icons/simple-icons/actions/runs/12449683970/job/34766897205

I've tested the code on my local with `npm run preview`.

### CODE REVIEW

**Comment by mondeja** [comment]
Could you create a new release?

**Comment by mondeja** [comment]
Didn't worked, see https://github.com/simple-icons/simple-icons/actions/runs/12457034998/job/34771141728

Reopened #88

**Comment by LitoMore** [comment]
You need to sync all changes to v1 branch. The v1 branch is used for release.

Passing now: https://github.com/simple-icons/simple-icons/pull/12422

**Comment by mondeja** [comment]
Ah, I see.

> Never create a v1 tag, as this will cause the actions only to get the commit of the tag.

A lot of acions (all that I saw before in fact) just use a force push of the tag. IMHO, branches has some drawbacks, for example, you need to maintain all major version branches and resolve conflicts on merges.

**Pull request merged**
